id: PE1A6A6D9
initial_creation_type: input
source_metadata:
  title: Tsok Series
  language: bo
  description: 'Lotsawa House presents the following texts related to the practice
    of tsok (tshogs) or feast-gathering (Skt. gaṇacakra):'
  volume:
    d0bdd4de5c9548eb9943fcdc37f2757d:
      title: Introduction to Gaṇacakra (Tsok)
      parent: Introduction
    63ff8976373c421d9b6637a9e0d8afa5:
      title: A Concise Explanation of Gaṇacakra
      parent: Explanation
    6fad1e833770402da9fc0b08047f45cb:
      title: 'A Bouquet of Uḍumbara Flowers: An Explanation of the Tenth Day'
      parent: Explanation
    a39b4902f1544afd8e6a1a41e48ec96b:
      title: 'Music to Adorn the Illusory Display: A Concise Explanation of the Nature
        of the Feast Offering'
      parent: Explanation
    92216f3f416541b69c39c15ce67830c4:
      title: The Gaṇacakra Ritual
      parent: Explanation
    7df7697a91174a0da2c3104b76f430b2:
      title: 'Sweet Droplets of the Honey of Accomplishment: A Concise Explanation
        of the Indispensable Points of the Feast-Gathering'
      parent: Explanation
    e243d25f2f3c4de397a4695a3573536d:
      title: 'Bestowing the Glory of Wisdom: A Gaṇacakra Feast for Nyingtik Saldrön'
      parent: Offering Liturgies
    c13b7ed222724c3ea2c184d65e48ee3b:
      title: 'A Glorious Garland of the Two Accomplishments: An Abridged Feast-Offering
        for the Female Practice of the Ḍākinī'
      parent: Offering Liturgies
    acac3168667b4235977774e7210ee681:
      title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
        Heart Drop'
      parent: Prayers
    f85e2014e11446c385a66190c97ffc8b:
      title: 'Essence of Accomplishment: A Concise Feast-Offering to Noble Tārā'
      parent: Prayers
    66734d2de5cc49f190bce81f7bf9e12d:
      title: Short Tsok Offering to the Powerful Lady Kurukullā
      parent: Prayers
    b724282100fa490793fc21af42ff9560:
      title: Brief Prayer of the Feast Gathering
      parent: Prayers
    b525c561af1843388416a84939523cf1:
      title: Confession and Fulfilment Insert for Accumulating the Practice of Turning
        Back the Summons of the Ḍākinīs
      parent: Prayers
    66a25585975b48c7accd09cede9e10de:
      title: Food Offering Prayer
      parent: Prayers
    1f674627f48248418dfee94b6550a0a2:
      title: Concise Tsok Feast
      parent: Prayers
    b9c819442a2140cd97d87a7c5343556a:
      title: 'Excellent Vase of Splendour: The Tsok Feast Offering to Accompany the
        Vajra Seven-Line Prayer'
      parent: Prayers
    02ecf02c1e6147da95d4d4ced9c3d160:
      title: A Concise Feast Prayer
      parent: Prayers
    838f656bfd60415fb89ec758e0f545be:
      title: Remainder Torma Offering for Seven-Line Prayer Guru Yoga
      parent: Remainder Offering
    fe4fb34fbd2840e28978813c1ce6269d:
      title: The Song of the Vajra
      parent: Songs
    0786fe1f06fa4a509b89c8968208404c:
      title: 'Ḍākinī’s Delight: A Song of the Feast'
      parent: Songs
    21ae0e7a640049d09a97bb288e9ce73c:
      title: 'Harmonious Clouds of Sublime and Lasting Bliss: A Vajra Song for the
        Tsok Feast Offering to Venerable and Exalted Vajrayoginī'
      parent: Songs
    f742a11b6c764e8980b1b9b731dbf4e8:
      title: 'Song and Dance to Delight the Ḍākas and Ḍākinīs: An Aspiration for the
        Sixfold Satisfaction of the Maṇḍala of the Feast-Gathering'
      parent: Songs
    7dd19cf280e1491a849a32ec0ca813d4:
      title: Song of the Feast (Tsok Lu)
      parent: Songs
created_at: '2022-03-01T06:26:39.650201'
last_modified_at: '2022-03-01T06:26:39.650203'
statistics:
  total_words: 29690
  total_non_words: 3215
quality:
  non_words_ratio: 0.11
